### ISSUE TITLE
Upon clicking the Read Full Story on first slide, some text briefly appears before popup

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/website#1]
Zipped video uploaded.
[video.zip](https://github.com/eka-foundation/website/files/2957082/video.zip)

This does not happen when the links on the second and third slides are clicked.

**Comment by mikkokotila** [comment]
I can't open the video, but what is the text? is it "32"?

**Comment by m-anish** [comment]
Yes!

**Comment by mikkokotila** [comment]
No more! Closing.

**Comment by m-anish** [comment]
I can confirm this is fixed! Thanks.
