### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/website#12]
As evident in the screenshot. 
![eka-broken](https://user-images.githubusercontent.com/5288668/54210584-c98b1880-4505-11e9-981a-f14cd1e5813f.png)

Perhaps this is a WIP, but still opening the issue anyway.

**Comment by mikkokotila** [comment]
Clear your cache and try again. I was able to reproduce it, but it had something to do with browser cache. Hard to understand how it could happen though. What happens there is CSS is not loaded, so you see how the site looks like when no CSS is loaded. So I think maybe server issue? No changes have been made to the site that could cause something like this.

**Comment by m-anish** [comment]
Yeah, Odd!

It is working now.

**Comment by mikkokotila** [comment]
By the way, at that very same time, I posted 5 new issues, but when I checked Git, there was none. Then suddenly I got kicked out of everything. So maybe something was wrong with the internetz more widely at that moment...I think today is 30 year bday for www.
