### ISSUE TITLE
On mobile, instead of fading, the images scroll

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/website#2]
On desktop, upon scrolling down, the images fade into the next slide's image, but on mobile, the images don't fade but rather scroll. Should we just scroll the text and keep the image static (perhaps the third one) for mobile?

**Comment by mikkokotila** [comment]
The way it will be done eventually, is that the new picture fades-in on top of the previous one.

**Comment by mikkokotila** [comment]
It fades now, so closing.
