### ISSUE TITLE
On Galaxy/Iphone emulator, the second slide's text should be better hyphenated. 

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/website#4]
The second slide's text breaks at:

* decentraliz--ed on Galaxy S5
* decental -- ized on Iphone X
* decetraliz -- ed  on iphone 6/7/8

Maybe there is a way to keep this consistent. Like break it at a certain place in all cases.

**Comment by mikkokotila** [comment]
This is now resolved. Basically the header text has to be on `font-size: 1.2vmax` i.e. `vmax` is the right way to do it so the size becomes viewport sensitive and picks either horizontal or vertical max to be 1.2.
