### ISSUE TITLE
Suggestions for Soujanyaa's blob

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/website#7]
Perhaps consider these edits?

“EKA’s research focus on encouraging discovery and learning as a creative process that empowers and inspires people to use technology in a meaningful way.~~Thriving towards the success of our mission,~~ Everything we do puts the people in the communities first. We are also responsible for technology developers, designers, and other professionals who work with us to make it possible to reach our ~~audacious~~ goals. We thrive to provide inclusive and inspiring career opportunities, where personal and work values are naturally aligned. In addition to the communities we work in, we share the wider concern with the future of key internet technologies, and the way in which such technologies influence people and affect their lives.”

**Comment by mikkokotila** [comment]
Done. Closing.
